development:
  bucket: carriemail-pdf-dev
  access_key_id: AKIAJH6PB433TWJOE4ZA
  secret_access_key: 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

test:
  bucket: carriemail-pdf-test
  access_key_id: AKIAJH6PB433TWJOE4ZA
  secret_access_key: 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

production:
  bucket: carriemail-pdf-production
  access_key_id: AKIAJH6PB433TWJOE4ZA
  secret_access_key: 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